http.port=8211
http.servlet.session.timeout=60
http.servlet.session.cookie.max-age=60
http.error.include-message=always
server.port=8800


phonepe.auth-url=https://api-preprod.phonepe.com/apis/pg-sandbox/v1/oauth/token
phonepe.pay-url=https://api-preprod.phonepe.com/apis/pg-sandbox/checkout/v2/pay
#phonepe.redirect-url=http://localhost:8080/api/phonepe/callback
phonepe.status-url=https://api-preprod.phonepe.com/apis/pg-sandbox/checkout/v2/order

# Credentials  
phonepe.client-id=M23XQU6CIYB75_2603131536
phonepe.client-secret=MWYyZmQyYTAtZjE0ZS00ODdkLTlkYjItMWQwZDdhMjE2YWE5
phonepe.client-version=1



spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.datasource.url=jdbc:sqlserver://evya.cjww6csio9ka.eu-north-1.rds.amazonaws.com:1433;databaseName=evya;useLOBs=false;serverTimezone=UTC
spring.datasource.url=jdbc:sqlserver://13.201.20.136:1433;databaseName=evya;useLOBs=false;serverTimezone=UTC
spring.datasource.username=sa
spring.datasource.password=ChargeEvya@1234

#spring.datasource.url=jdbc:mysql://127.0.0.1:3306/test_evya?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

#////////////////////////////////////////////uncomment for previous db////////////////////////////////////////
# Hibernate
hibernate.dialect: org.hibernate.dialect.SQLServerDialect
hibernate.show_sql: false
hibernate.hbm2ddl.auto: update
hibernate.packagesToScan: com.ewe.pojo
hibernate.enable_lazy_load_no_trans=true
hibernate.jdbc.batch_size = 50
hibernate.jdbc.time_zone=UTC

spring.main.banner-mode=off
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.debug=true
google.maps.api.key=AIzaSyCBkBMkpv_sE4TLE3ERGQBvL5A1kjdJCkg
hibernate.search.default.directory_provider=filesystem
hibernate.search.default.indexBase=C:/hibernate/lucence/indexes
hibernate.search.default.indexwriter.infostream=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui-custom.html
springdoc.swagger-ui.operationsSorter=method

# Beckn Configuration
beckn.default.search.radius.km=10
beckn.default.page.size=10
beckn.domain=nic2004:52110
beckn.city=Bengaluru
beckn.country=IND
#
#twilio.AccountSID=AC0f7af884df1d563d11343287a1ed9b83
#twilio.AuthToken=d0a6607e271350691894e038780d22a1
#twilio.phoneNumber=+16062892771
twilio.AccountSID=ACea1d6877ffc50389d95f0fad3270abfe
twilio.AuthToken=45bee5be968b0f90e07d3e6f17829f6f
twilio.phoneNumber=+16076955987

spring.mail.username=chargeevya@gmail.com
spring.mail.password=dfce yppw cfut qcaf
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

admin.email=jayavarapu17@gmail.com
admin.name=Admin
rfid.unit.price=300

razorpay.key.id=rzp_test_z51wLt0JB2gGzV
razorpay.secret.key=iZYcsJ1YNogZxvx8Qv0lnaje
