package com.ewe.pojo;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Site generated by hbm2java
 */
@Entity
@Table(name = "usersinroles")
@JsonIgnoreProperties(ignoreUnknown = true, value = { "user" })
public class Usersinroles implements Serializable {

	private static final long serialVersionUID = 1L;

	private Long role_id;
	private User user;

	@Id
	@ManyToOne(fetch = FetchType.LAZY, targetEntity = User.class)
	@JoinColumn(name = "user_id", nullable = false, unique = true)
	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "role_id", nullable = false)
	public Long getRole_id() {
		return this.role_id;
	}

	public void setRole_id(Long role_id) {
		this.role_id = role_id;
	}
}